import logging
import os
import socket
import threading
import time

import docker
from navipod_config import settings

client = docker.from_env()
DATA_ROOT = f"{settings.MUSIC_ROOT}"  # Ruta interna del contenedor (/saas-data/users)
logger = logging.getLogger(__name__)

# --- GLOBAL IP CACHE ---
# Avoids saturating the system with constant Health Checks
# Estructura: { "username": ("172.xx.xx.xx", timestamp) }
ip_cache = {}
_pool_status_lock = threading.Lock()
_pool_status_cache = {
    "measure_root": None,
    "used_bytes": 0,
    "timestamp": 0.0,
}

def provision_user_env(username: str):
    """Creates folders and initial configuration"""
    user_dir = f"{DATA_ROOT}/{username}"
    
    # Create all required directories with open permissions
    dirs_to_create = [
        f"{user_dir}/data",
        f"{user_dir}/music",
        f"{user_dir}/music/playlists",
        f"{user_dir}/music/Library",  # For downloaded tracks
    ]
    
    for dir_path in dirs_to_create:
        os.makedirs(dir_path, mode=0o777, exist_ok=True)
        try:
            # Force permissions even if directory existed
            os.chmod(dir_path, 0o777)
        except Exception:
            pass
    
    logger.info("Provisioned user environment for %s", username)

def wait_for_port(ip, port, timeout=15):
    """Waits until the port responds or times out"""
    # print(f"[HEALTH-CHECK] Waiting for {ip}:{port}...") # Commented out to clean logs
    start_time = time.time()
    while time.time() - start_time < timeout:
        try:
            with socket.create_connection((ip, port), timeout=1):
                # print(f"[HEALTH-CHECK] Success connection with {ip}!")
                return True
        except (OSError, ConnectionRefusedError):
            time.sleep(0.5)
    return False

def get_or_spawn_container(username: str):
    # 1. CHECK CACHE: If we have it and it's less than 5 min old, return directly
    if username in ip_cache:
        ip, timestamp = ip_cache[username]
        if time.time() - timestamp < 300:
            # Additional check: Does the container still exist?
            try:
                client.containers.get(f"navidrome-{username}")
                return ip
            except:
                del ip_cache[username] # Stale cache, delete.

    container_name = f"navidrome-{username}"
    
    try:
        container = client.containers.get(container_name)
        if container.status != "running":
            container.start()
            # Wait a bit for it to start if it was stopped
            time.sleep(1)
            
    except docker.errors.NotFound:
        logger.info("Creating Navidrome container for %s", username)
        container = client.containers.run(
            image=settings.NAVIDROME_IMAGE,
            name=container_name,
            detach=True,
            network="navipod-global", # Ensure this network exists in your docker-compose
            environment={
                "ND_BASEURL": f"/{username}",
                "ND_MUSICROOT": "/music",
                "ND_LOGLEVEL": "info",
                "ND_PORT": "4533",
                "ND_SCANSCHEDULE": "1h",
                "ND_REVERSEPROXYUSERHEADER": "x-navidrome-user",
                "ND_REVERSEPROXYWHITELIST": settings.NAVIDROME_REVERSE_PROXY_WHITELIST,
                "ND_ENABLELOGINFORM": "false",
                "ND_PROMOTEUSERTOADMIN": "true",
                "ND_ENABLEUSEREDITING": "false",
                "ND_DEFAULTTHEME": "Spotify-ish"
            },
            volumes={
                # Data persistence
                f"{settings.HOST_DATA_ROOT}/users/{username}/data": {'bind': '/data', 'mode': 'rw'},
                # Global Music Pool (Shared, Read-Only)
                f"{settings.HOST_DATA_ROOT}/pool": {'bind': '/music/Library', 'mode': 'ro'},
                # User Playlists (Private, Read-Write) - Mounted so M3U files generated by Navipod are seen
                f"{settings.HOST_DATA_ROOT}/users/{username}/music/playlists": {'bind': '/music/Playlists', 'mode': 'rw'} 
            }
        )
    
    # Reload info to get updated IP
    container.reload()
    # Automatically detect network (in case name changes)
    networks = container.attrs['NetworkSettings']['Networks']
    if 'navipod-global' in networks:
        ip_address = networks['navipod-global']['IPAddress']
    else:
        # Fallback: pick the first network found
        ip_address = list(networks.values())[0]['IPAddress']
    
    # 2. HEALTH CHECK (Only if not in cache or just started)
    if wait_for_port(ip_address, 4533):
        # 3. SAVE TO CACHE
        ip_cache[username] = (ip_address, time.time())
        return ip_address
    else:
        raise Exception(f"Navidrome at {ip_address} did not respond after 15s. Check logs.")
    
def stop_user_container(username: str):
    """Detiene y elimina el contenedor del usuario para liberar recursos"""
    container_name = f"navidrome-{username}"
    try:
        container = client.containers.get(container_name)
        if container.status == "running":
            logger.info("Stopping container %s", container_name)
            container.stop()
        
        logger.info("Removing container %s", container_name)
        container.remove()
        
        # Limpiar caché si existe
        if username in ip_cache:
            del ip_cache[username]
            
    except docker.errors.NotFound:
        pass # Ya no existe
    except Exception as e:
        logger.warning("Failed to remove container %s: %s", container_name, e)
    
def get_dir_size(path):
    """Calcula el tamaño total de un directorio en bytes de forma recursiva."""
    total = 0
    try:
        if not os.path.exists(path):
            return 0
        # Scandir es más rápido que walk para estas tareas
        with os.scandir(path) as it:
            for entry in it:
                if entry.is_file():
                    total += entry.stat().st_size
                elif entry.is_dir():
                    total += get_dir_size(entry.path)
    except Exception as e:
        logger.warning("Failed to measure disk usage for %s: %s", path, e)
        pass
    return total

def invalidate_pool_status_cache():
    with _pool_status_lock:
        _pool_status_cache["timestamp"] = 0.0


def _measure_pool_bytes(force_refresh: bool = False):
    measure_root = os.path.dirname(DATA_ROOT.rstrip('/'))
    if not measure_root or measure_root == "/":
        measure_root = "/saas-data"

    now = time.time()
    ttl = max(int(getattr(settings, "POOL_STATUS_CACHE_TTL_SECONDS", 60) or 0), 0)

    with _pool_status_lock:
        cache_fresh = (
            not force_refresh
            and ttl > 0
            and _pool_status_cache["measure_root"] == measure_root
            and now - float(_pool_status_cache["timestamp"] or 0) < ttl
        )
        if cache_fresh:
            return int(_pool_status_cache["used_bytes"] or 0)

    used_bytes = get_dir_size(measure_root)
    with _pool_status_lock:
        _pool_status_cache.update({
            "measure_root": measure_root,
            "used_bytes": used_bytes,
            "timestamp": time.time(),
        })
    return used_bytes


def get_pool_status(db, force_refresh: bool = False):
    """
    Retorna (used_gb, limit_gb, percent) del Global Pool.
    Calcula el uso total de HOST_DATA_ROOT (/saas-data).
    Lee el limit_gb de SystemSettings.
    """
    try:
        # 1. Calcular uso total del disco (Global). This recursive scan is
        # cached because admin/system screens poll it frequently.
        used_bytes = _measure_pool_bytes(force_refresh=force_refresh)
        used_gb = used_bytes / (1024**3)
        
        # 2. Obtener Límite Global
        # Importación local para evitar ciclo
        from database import SystemSettings
        
        sys_settings = db.query(SystemSettings).first()
        if not sys_settings:
            sys_settings = SystemSettings(pool_limit_gb=100)
            db.add(sys_settings)
            db.commit()
            
        limit_gb = sys_settings.pool_limit_gb
        
        percent = (used_gb / limit_gb) * 100 if limit_gb > 0 else 0
        return round(used_gb, 2), limit_gb, round(min(percent, 100), 1)
        
    except Exception as e:
        logger.warning("Failed to compute pool quota status: %s", e)
        return 0.0, 100, 0.0
